blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:article_slug>/', views.article, name='article'),
    path('tags', views.all_tags, name='all_tags'),
    path('tags/<tag_name>', views.tag, name='tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', views.index)
]

blog/models.py
from django.db import models
from markdown import markdown


class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    tag_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.tag_name


class Article(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, unique=True)

    pub_date = models.DateTimeField()
    content = models.TextField()
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def render_content_markdown(self):
        return markdown(self.content)

blog/views.py
from django.shortcuts import render
from .models import Article, Tag


def index(request):
    context = {
        "articles": Article.objects.order_by('-pub_date')
    }
    return render(request, 'blog/index.html', context)


def article(request, article_slug):
    article = Article.objects.get(slug__exact=article_slug)
    context = {
        "article": article,
    }
    return render(request, 'blog/article.html', context)


def all_tags(request):
    tags = Tag.objects.all()
    context = {
        "tags": tags
    }
    return render(request, 'blog/all_tags.html', context)


def tag(request, tag_name):
    selected_tag = Tag.objects.get(tag_name=tag_name)
    context = {
        "tag": selected_tag,
    }
    return render(request, 'blog/tag.html', context)

mysite/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    return HttpResponseRedirect(reverse('blog:index'))

blog/templates/blog/all_tags.html
{% extends 'blog/base.html' %}

{% block title %}All tags{{ tag.tag_name }}{% endblock %}

{% block body %}
    <h1>All tags</h1>
    <ul>
        {% for tag in tags %}
            <li><a href="{% url 'blog:tag' tag.tag_name %}">{{ tag.tag_name }}</a></li>
        {% endfor %}

    </ul>

{% endblock %}

blog/templates/blog/article.html
{% extends 'blog/base.html' %}

{% block head %}
    {{ block.super }}
    <script type="text/javascript" id="MathJax-script" async
            src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
    </script>
{% endblock head %}


{% block title %}
    article.title
{% endblock %}

{% block body %}

    <article class="blog_post">

        <h1> {{ article.title }}</h1>

        <div class="article_details">

            <h3 class="article_details">published: {{ article.pub_date }} UTC</h3>
            <h3 class="article_details">by: {{ article.author }}</h3>
            {% for tag in article.tags.all %}
                <h3 class="tags"><a href="{% url 'blog:tag' tag.tag_name %}">{{ tag.tag_name }}</a></h3>
            {% endfor %}

        </div>
        <p>

            {{ article.render_content_markdown|safe }}
        </p>
    </article>

{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
<head>
    {% block head %}
        <meta charset="utf-8">
        <title>{% block title %}Blog{% endblock %}</title>
        <meta name="description" content="{% block metacontent %}my amazing blog{% endblock %}">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    {% endblock head %}
</head>
<body>
{% block body %}
    <h1>Blog</h1>
{% endblock %}
</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block body %}
    <body>
    <h1>
        Blog
    </h1>
    <p>
        This is my blog
    </p>
    <h2>
        Recent Articles
    </h2>
    <ul>
        {% for article in articles %}
            <a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a>
        {% endfor %}
    </ul>

{% endblock %}

blog/templates/blog/tag.html
{% extends 'blog/base.html' %}

{% block title %}Tag: {{ tag.tag_name }}{% endblock %}

{% block body %}

    <h1>Tag: {{ tag.tag_name }}</h1>

    <ul>
        {% for article in tag.article_set.all %}
            <li>
                <p><a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a></p>
            </li>
        {% endfor %}
    </ul>

{% endblock %}